### ISSUE TITLE
failed to connect to database

### ISSUE THREAD

**Issue by frederikhors** [dosco/super-graph#36]
Using steps here: https://supergraph.dev/guide.html#get-started

specifically with this:

`docker-compose run blog_api ./super-graph db:setup`

I have this error:

```go
ERR connect failed err="failed to connect to `host=db user=postgres database=`: dial error (dial tcp: lookup db on 127.0.0.11:53: no such host)"
FTL app/serv/cmd_migrate.go:62 > failed to connect to database error="failed to connect to `host=db user=postgres database=`: dial error (dial tcp: lookup db on 127.0.0.11:53: no such host)"
```

**Comment by dosco** [comment]
I suspect this has to do with this change to the Posgres docker image. A quick fix for now is to change the line `image: postgres` in `docker-compose.yml` to `image: postgres:11.5` also be sure to run the below command firs

```console
docker-compose down
docker-compose run blog_api ./super-graph db:setup
```

**Comment by frederikhors** [comment]
I tried with 11.5, with 12, using these:

```yml
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
```

changing it also in `dev.yml` and `prod.yml` but it doesn't work.

I also used this:

```yml
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
```

```sql
CREATE DATABASE blog_development;
```

`ERR connect failed err="failed to connect to `host=db user=postgres database=`: dial error (dial tcp 172.25.0.2:5432: connect: connection refused)"`

I think it doesn't use the database name.

I will try to look better later.

**Comment by frederikhors** [comment]
Same problem here: https://supergraph.dev/guide.html#try-the-demo-app

```console
git clone https://github.com/dosco/super-graph
docker-compose run rails_app rake db:create db:migrate db:seed
```

```console
could not translate host name "db" to address: Name or service not known
Couldn't create 'app_development' database. Please check your configuration.
rake aborted!
PG::ConnectionBad: could not translate host name "db" to address: Name or service not known
/usr/local/bundle/gems/pg-1.1.4/lib/pg.rb:56:in `initialize'
/usr/local/bundle/gems/pg-1.1.4/lib/pg.rb:56:in `new'
/usr/local/bundle/gems/pg-1.1.4/lib/pg.rb:56:in `connect'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:46:in `postgresql_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:879:in `new_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:923:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:902:in `try_to_checkout_new_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:863:in `acquire_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:587:in `checkout'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:431:in `connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:1111:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_handling.rb:231:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_handling.rb:199:in `connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:126:in `create'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:185:in `block in create_current'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:476:in `each'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:475:in `each'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:184:in `create_current'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/railties/databases.rake:39:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:create
```

**Comment by frederikhors** [comment]
I managed to make it work by alternating these commands:

```console
docker-compose up
docker-compose run rails_app rake db:create db:migrate db:seed
```

After this:

```console
docker stop super-graph_super_graph_1
docker-compose up
```

It's needed because `db` is not up when I run `docker-compose run rails_app rake db:create db:migrate db:seed` and I think `Version 3 no longer supports the condition form of depends_on.` (https://docs.docker.com/compose/compose-file/) we need to find another way, maybe a script!

But I also think we need to create a repo for `demo` purpose only and we need to fix dependencies versions.

**Comment by frederikhors** [comment]
Also note I used this:

```yml
environment:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
```

because of this:

```
Error: Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD to a non-empty value for the
       superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
```

**Comment by frederikhors** [comment]
We also nee to change instructions on "HOW TO USE SUPER GRAPH?" section on https://supergraph.dev.

**Comment by dosco** [comment]
I suspect you are still not using 11.5 no password is required for 11.5 be sure to `docker-compose down` to delete all previous images.

**Comment by frederikhors** [comment]
Ok. Maybe.

But since from 12 onwards there is a need for a password I think the PR is fine, what do you think?
